### ISSUE TITLE
PUID/PGID problems

### ISSUE THREAD

**Issue by Juggler00** [dlandon/logitechmediaserver#6]
I have the following in my `docker-compose.yaml`:
```
  lms:
    image: dlandon/logitechmediaserver
    container_name: lms
    ports:
      - 9003:9000
      - 9090:9090
      - 3483:3483
    environment:
      - TZ=America/Toronto
      - PUID=1007    
      - PGID=1008
    volumes:
      - /docker/config:/config
      - /data/media/music:/music
```

On my hosting server, I have created a user "lms" with the following:
```
lms:x:1007:1008::/home/lms:/bin/sh
```

My existing music folder has been given the appropriate permissions for local user lms. However, the docker image process squeeboxserver cannot see it.

I notice on initial run the following in the logs:
```
usermod: group '1008' does not exist,
*** Running /etc/my_init.d/30_firstrun.sh...
```

Do the PUID and PGID environment variables work as intended?
